### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by tfafara** [Meadowcottage/devRant.io#1]
I tried to run the application on OS X 10.11.6, but it crashes immediately.

**Comment by Meadowcottage** [comment]
When you run the app, does the window open for a split second and then immediately close?

**Comment by tfafara** [comment]
Nope, it just crashes. See attached log.
[devrant.io.txt](https://github.com/Meadowcottage/devRant.io/files/318376/devrant.io.txt)

**Comment by Meadowcottage** [comment]
The issue appears to be with one of the images assets not being loaded. I'm going to look into this now and have the fix go out in the next update later today.

**Comment by Meadowcottage** [comment]
I have looked into this issue and it appears to be a bug with OSX itself. If you want some more details on it. Have a read of this issue of someone having a similar issue
https://github.com/electron-userland/electron-packager/issues/117

**Comment by Meadowcottage** [comment]
For now, I have found a temporary fix, copy

`Electron.app/Contents/Frameworks/Electron ` `Framework.framework/Versions/A/Libraries/libffmpeg.dylib`

and past it to: 

`/usr/local/lib`
