### ISSUE TITLE
1.0.1 OSX 

### ISSUE THREAD

**Issue by lquessenberry** [Meadowcottage/devRant.io#2]
http://puu.sh/puR6P/47f48b1eda.png

Says it can't be opened on my Mac.

**Comment by Meadowcottage** [comment]
Can I get some more information on your system such as whether it's a laptop or desktop. OSX version, etc.

**Comment by lquessenberry** [comment]
No prob!

http://puu.sh/puSdP/a36a01a5dc.png

**Comment by Meadowcottage** [comment]
Okay. Have you tried version 1.0.2 yet?
I made some small fixes that may have been causing crashes and I want to see if it has fixed this. If not I will look further into it.

**Comment by lquessenberry** [comment]
I didn't recall seeing a package for OSX on version 1.0.2. I will look again. ;)

**Comment by Meadowcottage** [comment]
If you continue to get the error in the new version. Try this in terminal:
chmod +x [directory]/devRant.io.app/Contents/MacOS/devRant.io

**Comment by lquessenberry** [comment]
Right on. I may be a bit behind you in smarts... Is there a binary for Mac OSX 1.0.2 that I can download or should I try that on 1.0.1?

**Comment by lquessenberry** [comment]
Nevermind. Didn't realize that the darwin package was it. 🌴
