### ISSUE TITLE
Link open inside the app

### ISSUE THREAD

**Issue by skywebdeveloper** [Meadowcottage/devRant.io#3]
Links open inside the app and there is not way to go back. Had to restart app everytime.

**Comment by Meadowcottage** [comment]
Are all links inside the app opening inside the window and not opening in the browser like they're supposed to?

**Comment by Mrbysco** [comment]
I've taken it upon me to see what exactly the person ment.

Basically some links will open the website within the app.
For example within the sticker section you are able to click multiple links and end up stuck on the Google Play website.

![Image of Google Play opened within the app](http://i.imgur.com/L8ubxih.png)

**Comment by skywebdeveloper** [comment]
I understand about some links will open inside the app like all links of devrant.io is expected to open in app.

What i am saying is all links embedded inside a rant is opened inside the app.

**Comment by Meadowcottage** [comment]
Can I get some more details on your setup. Operating System, OS version, app version, etc.

**Comment by skywebdeveloper** [comment]
Microsoft Windows 10 Pro Build 102586.318
devRant app version 1.0.2

**Comment by Meadowcottage** [comment]
Are you referring to the links inside of rants, like links to external sites like Youtube or Google or Github, etc?

**Comment by skywebdeveloper** [comment]
Yes i am referring to links inside a rant of external sites.

Share button on a rant open up a browser

**Comment by Meadowcottage** [comment]
I am aware that all links that usually link to an external site open in the Window. It is a known bug and I am working on a fix to see if there is a way to make all external links open in the default browser.
